title: Oniro
description:
theme: just-the-docs
logo: "/introduction-to-oniro/images/ONIRO-Masterbrand-horizontal.png"
color_scheme: oniro

baseurl: ""

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# External navigation links
# nav_external_links:
#   - title: Oniro Legacy Documentation
#     url: https://oniroproject.readthedocs.io/
#     hide_icon: false
#     opens_in_new_tab: false

callouts:
  warning:
    title: Warning
    color: red

  note:
    title: Note
    color: purple

  tip:
    title: Tip
    color: yellow